# Generated by Django 4.1.3 on 2022-11-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='playlist_song',
            field=models.ManyToManyField(to='music.playlist'),
        ),
    ]
