# Generated by Django 4.1.3 on 2022-11-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_albumsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.songs')),
            ],
        ),
    ]
