# Generated by Django 4.1.3 on 2022-11-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artistsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistSong',
            new_name='PlaylistSongs',
        ),
    ]
